import axios from "axios";

/*
|--------------------------------------------------------------------------
| PhonePe Configuration
|--------------------------------------------------------------------------
| Keep ALL PhonePe credentials on the backend.
|
| Example .env:
|
| PHONEPE_BASE_URL=https://api-preprod.phonepe.com/apis/pg-sandbox
| PHONEPE_CLIENT_ID=your_client_id
| PHONEPE_CLIENT_SECRET=your_client_secret
| PHONEPE_CLIENT_VERSION=1
| PHONEPE_REDIRECT_URL=https://your-frontend.com/payment/status
|
| IMPORTANT:
| Do NOT put these values in VITE_ variables.
|--------------------------------------------------------------------------
*/

const PHONEPE_BASE_URL = process.env.PHONEPE_BASE_URL;

const PHONEPE_CLIENT_ID = process.env.PHONEPE_CLIENT_ID;

const PHONEPE_CLIENT_SECRET = process.env.PHONEPE_CLIENT_SECRET;

const PHONEPE_CLIENT_VERSION = process.env.PHONEPE_CLIENT_VERSION || "1";

const PHONEPE_REDIRECT_URL = process.env.PHONEPE_REDIRECT_URL;

/*
|--------------------------------------------------------------------------
| Validate Configuration
|--------------------------------------------------------------------------
*/

const validatePhonePeConfig = () => {
  const missing = [];

  if (!PHONEPE_BASE_URL) {
    missing.push("PHONEPE_BASE_URL");
  }

  if (!PHONEPE_CLIENT_ID) {
    missing.push("PHONEPE_CLIENT_ID");
  }

  if (!PHONEPE_CLIENT_SECRET) {
    missing.push("PHONEPE_CLIENT_SECRET");
  }

  if (!PHONEPE_REDIRECT_URL) {
    missing.push("PHONEPE_REDIRECT_URL");
  }

  if (missing.length > 0) {
    throw new Error(
      `Missing PhonePe environment variables: ${missing.join(", ")}`,
    );
  }
};

/*
|--------------------------------------------------------------------------
| Axios Client
|--------------------------------------------------------------------------
*/

const phonePeClient = axios.create({
  timeout: 15000,

  headers: {
    "Content-Type": "application/json",
    Accept: "application/json",
  },
});

/*
|--------------------------------------------------------------------------
| Generate Merchant Order ID
|--------------------------------------------------------------------------
|
| This ID is generated by OUR backend.
|
| It should be unique for every payment attempt.
|
|--------------------------------------------------------------------------
*/

export const generateMerchantOrderId = (userId) => {
  const timestamp = Date.now();

  const randomPart = Math.random().toString(36).substring(2, 10);

  return `ESETU_${timestamp}_${userId.toString().slice(-6)}_${randomPart}`;
};

/*
|--------------------------------------------------------------------------
| Convert INR → Paise
|--------------------------------------------------------------------------
|
| PhonePe payment APIs generally work with the smallest
| currency unit.
|
| ₹980.50 → 98050 paise
|--------------------------------------------------------------------------
*/

export const rupeesToPaise = (amount) => {
  const numericAmount = Number(amount);

  if (!Number.isFinite(numericAmount) || numericAmount < 0) {
    throw new Error("Invalid payment amount.");
  }

  return Math.round(numericAmount * 100);
};

/*
|--------------------------------------------------------------------------
| Convert Paise → INR
|--------------------------------------------------------------------------
*/

export const paiseToRupees = (amount) => {
  const numericAmount = Number(amount);

  if (!Number.isFinite(numericAmount) || numericAmount < 0) {
    throw new Error("Invalid paise amount.");
  }

  return numericAmount / 100;
};

/*
|--------------------------------------------------------------------------
| Create PhonePe Payment
|--------------------------------------------------------------------------
|
| NOTE:
| The exact endpoint/body/authentication mechanism must match the
| PhonePe PG integration enabled for your merchant account.
|
| This function deliberately keeps that implementation isolated here.
|--------------------------------------------------------------------------
*/

export const createPhonePePayment = async ({
  merchantOrderId,
  amount,
  userId,
}) => {
  validatePhonePeConfig();

  if (!merchantOrderId) {
    throw new Error("Merchant order ID is required.");
  }

  if (!userId) {
    throw new Error("User ID is required.");
  }

  const amountInPaise = rupeesToPaise(amount);

  if (amountInPaise <= 0) {
    throw new Error("Payment amount must be greater than zero.");
  }

  /*
  |--------------------------------------------------------------------------
  | PhonePe Request
  |--------------------------------------------------------------------------
  |
  | Keep this object in ONE place.
  |
  | Once your PhonePe onboarding is approved and they provide the
  | exact API credentials/version, this is the only service that
  | should need adjustment.
  |--------------------------------------------------------------------------
  */

  const payload = {
    merchantOrderId,

    amount: amountInPaise,

    paymentFlow: {
      type: "PG_CHECKOUT",
    },

    redirectUrl: PHONEPE_REDIRECT_URL,
  };

  try {
    const response = await phonePeClient.post(
      `${PHONEPE_BASE_URL}/checkout/v2/pay`,

      payload,

      {
        headers: {
          "Content-Type": "application/json",
          Accept: "application/json",

          /*
           * These are intentionally kept here rather than exposed
           * to the frontend.
           */
          "X-CLIENT-ID": PHONEPE_CLIENT_ID,
          "X-CLIENT-VERSION": PHONEPE_CLIENT_VERSION,
          "X-CLIENT-SECRET": PHONEPE_CLIENT_SECRET,
        },
      },
    );

    return {
      success: true,

      data: response.data,
    };
  } catch (error) {
    console.error(
      "PhonePe create payment error:",
      error.response?.data || error.message,
    );

    const phonePeMessage =
      error.response?.data?.message ||
      error.response?.data?.error ||
      error.message ||
      "PhonePe payment creation failed.";

    throw new Error(phonePeMessage);
  }
};

/*
|--------------------------------------------------------------------------
| Get PhonePe Payment Status
|--------------------------------------------------------------------------
|
| This will be used after the user returns from PhonePe and/or
| when handling the payment callback.
|--------------------------------------------------------------------------
*/

export const getPhonePePaymentStatus = async (merchantOrderId) => {
  validatePhonePeConfig();

  if (!merchantOrderId) {
    throw new Error("Merchant order ID is required.");
  }

  try {
    const response = await phonePeClient.get(
      `${PHONEPE_BASE_URL}/checkout/v2/order/${encodeURIComponent(
        merchantOrderId,
      )}/status`,
      {
        headers: {
          Accept: "application/json",

          "X-CLIENT-ID": PHONEPE_CLIENT_ID,
          "X-CLIENT-VERSION": PHONEPE_CLIENT_VERSION,
          "X-CLIENT-SECRET": PHONEPE_CLIENT_SECRET,
        },
      },
    );

    return {
      success: true,

      data: response.data,
    };
  } catch (error) {
    console.error(
      "PhonePe payment status error:",
      error.response?.data || error.message,
    );

    const phonePeMessage =
      error.response?.data?.message ||
      error.response?.data?.error ||
      error.message ||
      "Unable to check PhonePe payment status.";

    throw new Error(phonePeMessage);
  }
};

/*
|--------------------------------------------------------------------------
| Normalize PhonePe Status
|--------------------------------------------------------------------------
|
| Different API responses can contain status information in
| different places depending on the integration/version.
|
| We normalize it here so the controller doesn't care about
| PhonePe's response structure.
|--------------------------------------------------------------------------
*/

export const normalizePhonePeStatus = (response) => {
  if (!response) {
    return "PENDING";
  }

  const status =
    response?.state ||
    response?.status ||
    response?.data?.state ||
    response?.data?.status ||
    response?.orderState ||
    response?.data?.orderState;

  if (!status) {
    return "PENDING";
  }

  const normalized = String(status).toUpperCase();

  /*
  |--------------------------------------------------------------------------
  | SUCCESS
  |--------------------------------------------------------------------------
  */

  if (
    normalized === "SUCCESS" ||
    normalized === "COMPLETED" ||
    normalized === "PAID"
  ) {
    return "SUCCESS";
  }

  /*
  |--------------------------------------------------------------------------
  | FAILED
  |--------------------------------------------------------------------------
  */

  if (
    normalized === "FAILED" ||
    normalized === "FAILURE" ||
    normalized === "CANCELLED" ||
    normalized === "CANCELED"
  ) {
    return "FAILED";
  }

  /*
  |--------------------------------------------------------------------------
  | EXPIRED
  |--------------------------------------------------------------------------
  */

  if (normalized === "EXPIRED" || normalized === "TIMEOUT") {
    return "EXPIRED";
  }

  /*
  |--------------------------------------------------------------------------
  | Everything else
  |--------------------------------------------------------------------------
  */

  return "PENDING";
};

/*
|--------------------------------------------------------------------------
| Extract PhonePe Transaction ID
|--------------------------------------------------------------------------
*/

export const extractPhonePeTransactionId = (response) => {
  return (
    response?.transactionId ||
    response?.providerReferenceId ||
    response?.data?.transactionId ||
    response?.data?.providerReferenceId ||
    response?.paymentDetails?.[0]?.transactionId ||
    response?.data?.paymentDetails?.[0]?.transactionId ||
    null
  );
};

/*
|--------------------------------------------------------------------------
| Export Configuration Helper
|--------------------------------------------------------------------------
|
| Useful for checking whether PhonePe credentials have been
| configured without exposing the actual secret.
|--------------------------------------------------------------------------
*/

export const isPhonePeConfigured = () => {
  return Boolean(
    PHONEPE_BASE_URL &&
    PHONEPE_CLIENT_ID &&
    PHONEPE_CLIENT_SECRET &&
    PHONEPE_REDIRECT_URL,
  );
};
