import mongoose from "mongoose";

const paymentSchema = new mongoose.Schema(
  {
    // ============================================
    // USER
    // ============================================
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true,
    },

    // ============================================
    // MERCHANT PAYMENT ID
    // ============================================
    // Unique ID generated by OUR backend.
    // This ID is sent to PhonePe as the merchant
    // transaction/order reference.
    // ============================================
    merchantOrderId: {
      type: String,
      required: true,
      unique: true,
      index: true,
      trim: true,
    },

    // ============================================
    // PHONEPE TRANSACTION ID
    // ============================================
    // Filled after PhonePe gives us a transaction ID.
    // ============================================
    phonePeTransactionId: {
      type: String,
      default: null,
      index: true,
      trim: true,
    },

    // ============================================
    // AMOUNT BEFORE DISCOUNT
    // ============================================
    originalAmount: {
      type: Number,
      required: true,
      min: 0,
    },

    // ============================================
    // ONLINE PAYMENT DISCOUNT
    // ============================================
    discount: {
      type: Number,
      default: 0,
      min: 0,
    },

    // ============================================
    // ACTUAL AMOUNT TO PAY
    // ============================================
    amount: {
      type: Number,
      required: true,
      min: 0,
    },

    // ============================================
    // PAYMENT METHOD
    // ============================================
    paymentMethod: {
      type: String,
      enum: ["ONLINE"],
      default: "ONLINE",
      required: true,
    },

    // ============================================
    // PAYMENT STATUS
    // ============================================
    status: {
      type: String,
      enum: ["PENDING", "SUCCESS", "FAILED", "EXPIRED"],
      default: "PENDING",
      index: true,
    },

    // ============================================
    // ORDER
    // ============================================
    // This remains null until payment succeeds
    // and the Order is created.
    // ============================================
    orderId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Order",
      default: null,
      index: true,
    },

    // ============================================
    // PHONEPE RESPONSE DATA
    // ============================================
    // Useful for debugging/reconciliation.
    // Don't store sensitive secrets here.
    // ============================================
    phonePeResponse: {
      type: mongoose.Schema.Types.Mixed,
      default: null,
    },

    // ============================================
    // PAYMENT FAILURE REASON
    // ============================================
    failureReason: {
      type: String,
      default: null,
      trim: true,
    },

    // ============================================
    // PAYMENT EXPIRY
    // ============================================
    expiresAt: {
      type: Date,
      default: null,
      index: true,
    },
  },

  {
    timestamps: true,
  },
);

// ============================================
// OPTIONAL INDEXES
// ============================================

// Quickly find a user's pending payments
paymentSchema.index({
  userId: 1,
  status: 1,
});

// Quickly find payments created recently
paymentSchema.index({
  createdAt: -1,
});

const Payment = mongoose.model("Payment", paymentSchema);

export default Payment;
